<?php
declare(strict_types=1);

return [
    'id' => '44133221-b4a8-58f2-82dc-564184cbb701',
    'supplier_external_id' => '57746',
    'supplier_sku' => 'SE-EWF897',
    'ean' => '8435764446733',
    'name' => 'Cauciuc plin 9×3.0-5.5 AMITOR pentru KuKirin G2 Pro 2024',
    'slug' => 'cauciuc-plin-9x3-5-5-kukirin-g2-pro-2024',
    'short_description' => 'Scapă de penele care îți întrerup traseul. Varianta AMITOR 9×3.0-5.5 are profil mixt și interior elastic, fiind destinată KuKirin G2 Pro 2024 după confirmarea jantei.',
    'description_title' => 'Cauciuc anti-pană 9×3.0-5.5: alegere, compatibilitate și montaj',
    'meta_title' => 'Cauciuc plin 9x3-5.5 KuKirin G2 Pro 2024 | G-Trots',
    'meta_description' => 'Cauciuc plin anti-pană 9x3-5.5 pentru KuKirin G2 Pro 2024, profil mixt și interior elastic. Verificare compatibilitate și montaj la G-Trots.',
    'description_html' => <<<'HTML'
<p>Un cauciuc plin pentru trotinetă electrică este ales, de regulă, dintr-un motiv foarte clar: vrei să nu mai oprești traseul din cauza unei camere înțepate, a unei valve rupte sau a unei pierderi lente de presiune. Modelul AMITOR 9×3.0-5.5 este o anvelopă solidă, fără cameră și fără aer, construită pentru o jantă compatibilă de 5,5 inch. Profilul lat, cu blocuri pronunțate, și golurile elastice din zona interioară îl diferențiază de un inel masiv simplu. Rezultatul urmărit este o rulare rezistentă la pană, cu o anumită capacitate de deformare, însă fără să pretindem că poate reproduce confortul unui cauciuc pneumatic.</p>

<p>Dimensiunea este partea care contează cel mai mult înainte de comandă. Inscripția 9×3.0-5.5 nu trebuie redusă la ideea generală de „cauciuc de 9 inch”. Prima valoare indică familia diametrului exterior, a doua arată lățimea nominală, iar 5,5 se referă la diametrul jantei pentru care este realizată zona de montaj. În imaginile produsului, anvelopa are aproximativ 215 mm diametru exterior și 75 mm lățime totală. Zona interioară are o deschidere măsurată aproximativ la 125–138 mm, iar canalul de așezare este prezentat la circa 48 mm. Aceste cote sunt utile pentru identificare, dar verificarea finală se face întotdeauna pe trotineta reală, deoarece aceeași denumire comercială poate exista în revizii diferite.</p>

<p><strong>Compatibilitatea principală urmărită este KuKirin G2 Pro 2024</strong>, în versiunea echipată din fabrică sau adaptată corect pentru dimensiunea 9×3.0-5.5. Aici anul și revizia nu sunt un detaliu de marketing. Pe piață există variante G2 Pro asociate cu alte dimensiuni, inclusiv generații mai vechi pentru care acest cauciuc nu trebuie comandat doar după numele modelului. Verifică inscripția anvelopei actuale, diametrul jantei și spațiul disponibil în furcă sau basculă. Dacă marcajul nu este lizibil, trimite echipei G‑Trots fotografii clare cu roata, janta și modelul trotinetei. Confirmarea înainte de plată este mai simplă decât returul unei anvelope care arată asemănător, dar nu se poate așeza corect.</p>

<p>Acest model este numit frecvent cauciuc plin, anvelopă solidă, cauciuc anti-pană sau anvelopă fără cameră. Toate aceste expresii descriu același avantaj de bază: nu există o cameră cu aer care să fie perforată de sticlă, sârmă, cuie sau ciupită între anvelopă și jantă. Nu vei avea presiune de verificat săptămânal și nu vei rămâne cu roata moale din cauza unei valve defecte. Pentru naveta zilnică, livrări, deplasări repetate sau trasee unde o pană produce întârzieri serioase, această predictibilitate poate cântări mai mult decât plusul de confort oferit de o anvelopă pneumatică.</p>

<p>Avantajul anti-pană nu înseamnă însă că roata devine indestructibilă. Cauciucul se uzează, profilul se poate rotunji, materialul poate îmbătrâni, iar o montare incorectă poate deteriora janta sau poate lăsa anvelopa necentrată. De asemenea, loviturile puternice nu mai sunt absorbite de o pernă de aer. O parte mai mare din șoc ajunge în jantă, rulmenți, brațe, ghidon și corpul conducătorului. Alegerea corectă nu este „plin este întotdeauna mai bun”, ci „plin este potrivit atunci când prioritatea mea este eliminarea penelor și accept o rulare mai fermă”. O descriere onestă trebuie să păstreze ambele părți ale deciziei.</p>

<p>Structura interioară cu deschideri longitudinale este importantă. În loc să fie o masă compactă de cauciuc de la bandă până la jantă, modelul are goluri distribuite în zona care se comprimă în mers. Acestea permit materialului să lucreze ușor la trecerea peste rosturi, piatră cubică sau denivelări mici. Vei întâlni uneori denumirea comercială „honeycomb”, deși forma exactă a canalelor diferă între producători. În cazul de față, fotografiile arată fante interioare alungite, nu faguri exteriori deschiși. Ele pot reduce rigiditatea față de un cauciuc complet compact, dar nu transformă anvelopa într-una cu aer și nu elimină vibrațiile.</p>

<p><strong>Profilul de rulare este lat și segmentat</strong>, cu blocuri mari dispuse pe centru și pe umeri. Aspectul este apropiat de un profil mixt, potrivit pentru asfalt urban, pavele și porțiuni ocazionale cu suprafață mai puțin uniformă. Muchiile multiple pot oferi puncte de contact utile pe praf sau pe un drum uscat cu granulație, dar anvelopa nu trebuie prezentată ca una profesională de off-road și nici ca o garanție de aderență pe ud. Aderența reală depinde de compus, temperatură, uzură, viteză, sarcină și suprafață. Pe marcaje rutiere ude, capace metalice, frunze sau nisip, accelerația și frânarea trebuie făcute progresiv indiferent de desenul profilului.</p>

<p>Lățimea de aproximativ 75 mm oferă o amprentă vizuală generoasă și trebuie corelată cu spațiul din jurul roții. Nu este suficient ca diametrul interior să intre pe jantă. Anvelopa trebuie să aibă loc față de aripă, etrier, șuruburi, braț și cabluri, inclusiv când suspensia lucrează sau roata flexează ușor sub sarcină. Un cauciuc prea lat poate freca permanent sau doar în viraje și la comprimare. Frecarea produce căldură, consum, zgomot și uzură neregulată. De aceea, măsurarea și comparația cu piesa existentă fac parte din montaj, nu sunt o formalitate făcută după ce produsul a fost deja forțat pe jantă.</p>

<p>Pentru un utilizator care vine de la o anvelopă pneumatică, prima diferență observată va fi răspunsul mai direct al roții. Trotineta poate părea mai precisă pe asfalt neted, deoarece nu mai există variația produsă de o presiune prea mică, dar poate transmite mai multe vibrații pe asfalt degradat. Confortul depinde și de suspensie, greutatea utilizatorului, viteza de rulare și poziția pe deck. Dacă trotineta are suspensie eficientă și este folosită în principal în oraș, compromisul poate fi acceptabil. Dacă traseul zilnic include multe borduri, gropi și piatră cubică, merită discutat cu service-ul dacă o anvelopă cu aer sau una tubeless ar rămâne alegerea mai echilibrată.</p>

<p>Un alt efect posibil este schimbarea autonomiei. O anvelopă plină nu pierde presiune, deci nu ajunge să ruleze accidental foarte moale, însă masa, compusul și deformarea ei pot modifica rezistența la rulare față de configurația originală. Nu este corect să promitem un număr fix de kilometri câștigați sau pierduți. Dacă după montaj observi un consum neobișnuit, verifică mai întâi dacă roata se învârte liber, dacă etrierul nu atinge discul, dacă anvelopa este centrată și dacă nu există frecare de aripă. O problemă mecanică de montaj poate influența autonomia mai mult decât tipul anvelopei în sine.</p>

<p><strong>Înainte să comanzi, compară următoarele elemente:</strong></p>
<ul>
  <li>marcajul complet de pe anvelopa montată acum, nu doar valoarea „9 inch”;</li>
  <li>modelul și anul trotinetei, în special dacă este KuKirin G2 Pro;</li>
  <li>diametrul și forma canalului jantei, inclusiv lățimea zonei de așezare;</li>
  <li>spațiul dintre anvelopă, aripă, etrier, braț și elementele de fixare;</li>
  <li>fotografia profilului și a flancului piesei originale;</li>
  <li>poziția roții, față sau spate, și eventualele modificări făcute anterior.</li>
</ul>

<p>Dacă una dintre aceste informații lipsește, nu încerca să compensezi alegând după fotografia generală a produsului. Două anvelope pot avea un profil aproape identic, dar o talonare diferită. La fel, o denumire precum „G2 Pro” nu garantează aceeași roată pentru toți anii. Echipa G‑Trots poate verifica mai repede compatibilitatea atunci când primește o fotografie laterală completă, un prim-plan cu inscripția și o imagine a jantei. Dacă trotineta a fost cumpărată second-hand, menționează acest lucru: roțile sau motorul pot fi deja schimbate, iar configurația reală contează mai mult decât fișa modelului din fabrică.</p>

<p>Montajul unui cauciuc plin este considerabil mai solicitant decât montajul unei camere. Materialul trebuie încălzit și flexibilizat controlat, janta trebuie protejată, iar anvelopa trebuie ghidată uniform peste margine fără tăieturi, deformări sau forțarea cablului motorului. Metoda exactă depinde de roată și de echipamentele disponibile. Improvizațiile cu șurubelnițe ascuțite pot marca janta, pot răni anvelopa și pot deteriora cablul unui motor integrat în roată. Încălzirea excesivă poate afecta materialul. Din aceste motive, pentru cine nu a mai făcut operația, montajul în service este de obicei varianta mai sigură și mai eficientă.</p>

<p><strong>Poți solicita montajul direct la service-ul G‑Trots.</strong> Înainte de programare, transmite modelul, anul, dimensiunea actuală și spune dacă roata conține motorul. La recepție se verifică janta, rulmenții, discul de frână, cablul motorului și spațiul disponibil. După montare, roata trebuie rotită și observată din mai multe unghiuri pentru a confirma că anvelopa este așezată uniform. Se verifică și dacă discul nu freacă, dacă piulițele sau șuruburile sunt strânse corect și dacă traseul cablului rămâne sigur. Montajul nu ar trebui tratat ca simpla împingere a cauciucului pe jantă, ci ca o intervenție asupra ansamblului roții.</p>

<p>După montaj, primele deplasări trebuie făcute controlat. Rulează la viteză redusă, fără viraje bruște și fără frânări maxime, până când te obișnuiești cu răspunsul diferit. Ascultă dacă apare un zgomot periodic și urmărește dacă ghidonul vibrează neobișnuit. O vibrație care crește odată cu viteza poate indica o așezare neuniformă, o jantă deformată sau o problemă existentă a rulmenților. Oprește și verifică ansamblul dacă anvelopa pare să „urce și să coboare” în timpul rotației. Nu presupune că orice comportament nou este normal doar pentru că anvelopa este plină.</p>

<p>Rodajul nu înseamnă că materialul trebuie să se muleze pe o jantă incompatibilă. Înseamnă doar că suprafața nouă a profilului și senzația la ghidon devin mai previzibile după câteva trasee prudente. Evită să testezi limita de aderență imediat după montaj. Pe vreme rece, compusul poate părea mai rigid; pe vreme foarte caldă, senzația se poate schimba. Aceste variații sunt normale pentru produse din cauciuc, dar fisurile, desprinderile, deformarea permanentă sau frecarea de alte componente nu sunt normale și trebuie verificate.</p>

<p>Întreținerea este simplă, nu inexistentă. Nu ai presiune de măsurat și nici cameră de înlocuit, însă merită să inspectezi periodic profilul, flancurile și așezarea pe jantă. Îndepărtează pietricelele prinse între blocuri și curăță anvelopa cu apă și o soluție blândă, fără solvenți agresivi care pot ataca materialul. Verifică roata după o lovitură puternică într-o groapă sau bordură. Chiar dacă anvelopa nu poate face pană, janta se poate îndoi, rulmenții pot căpăta joc, iar șuruburile se pot slăbi. Avantajul anti-pană nu înlocuiește inspecția mecanică.</p>

<p>Semnele de uzură nu se rezumă la dispariția completă a profilului. Urmărește dacă zona centrală devine plată, dacă blocurile se rup la margini, dacă apar crăpături adânci sau dacă anvelopa se deplasează pe jantă. O uzură accentuată pe o singură parte poate indica aliniere greșită, joc în braț sau rulment, ori un montaj neuniform. Dacă roata începe să vibreze după o perioadă în care a funcționat corect, verifică ansamblul înainte de a continua utilizarea. Înlocuirea la timp protejează și celelalte componente ale trotinetei.</p>

<p>Profilul mixt este potrivit pentru deplasări urbane și pentru porțiuni ocazionale cu asfalt imperfect, dar nu schimbă limitele unei trotinete electrice. Gropile, bordurile și denivelările trebuie abordate încet, cu genunchii ușor flexați și fără frânare bruscă exact în obstacol. Pe suprafețe umede, păstrează distanță mai mare și evită înclinarea agresivă. Cauciucul plin oferă liniște în privința penelor, nu imunitate la pierderea aderenței. Stilul de conducere rămâne principalul element de siguranță.</p>

<p>Pentru cei care compară această anvelopă cu un model tubeless de aceeași dimensiune, diferența principală este prioritatea. Tubeless păstrează o pernă de aer și, montat corect, poate oferi confort și aderență mai apropiate de configurația originală, dar poate pierde presiune și poate fi perforat. Varianta plină renunță la aer, reduce grijile legate de pană și valvă, însă rulează mai ferm. Nu există un câștig universal. Naveta zilnică pe asfalt relativ bun poate favoriza predictibilitatea anvelopei pline, în timp ce traseele foarte denivelate pot favoriza confortul unei anvelope cu aer.</p>

<p>Greutatea utilizatorului și sarcina transportată influențează senzația, dar nu publicăm o limită inventată pentru acest produs în lipsa unei valori certificate de producător. Respectă limita totală a trotinetei și nu interpreta construcția solidă drept permisiunea de a depăși sarcina admisă. O sarcină mare crește solicitarea în jantă, rulmenți, axe și suspensie. Dacă trotineta este folosită profesional sau transportă frecvent greutate suplimentară, o verificare periodică a ansamblului roții este cu atât mai importantă.</p>

<p>Producătorul asociat produsului este AMITOR, iar codul de furnizor este SE-EWF897. EAN-ul identificat pentru această variantă este 8435764446733. Aceste coduri ajută la separarea produsului de alte anvelope cu nume asemănător. Când soliciți verificare sau montaj, menționează codul dacă îl ai la îndemână. Pentru compatibilitate, codul și dimensiunile trebuie folosite împreună: EAN-ul confirmă varianta comercială, în timp ce măsurătorile și janta confirmă potrivirea pe trotineta concretă.</p>

<p><strong>De ce contează experiența unui service de trotinete?</strong> O roată nu funcționează izolat. La demontare pot deveni vizibile plăcuțe uzate, disc îndoit, rulment cu joc, ax slăbit sau cablu motor tensionat. Dacă se schimbă doar anvelopa fără observarea acestor elemente, clientul poate pleca cu o pană rezolvată, dar cu altă problemă nediagnosticată. G‑Trots este specializat în service pentru trotinete electrice, astfel încât poate verifica ansamblul și poate explica dacă această conversie la cauciuc plin este potrivită pentru modul tău de utilizare.</p>

<p>Înainte de conversia de la pneumatic la plin, discută și despre confort. Dacă ai dureri de spate, rulezi mult pe piatră cubică sau trotineta nu are suspensie eficientă, rigiditatea suplimentară poate fi importantă. Dacă principalul inconvenient actual îl reprezintă penele repetate produse de presiune incorectă, merită verificat mai întâi de ce apar. Uneori, o bandă de jantă deteriorată, o valvă montată greșit sau rularea constantă cu presiune mică provoacă probleme care pot fi rezolvate fără schimbarea tipului de anvelopă. Alegerea plinului trebuie să fie o decizie informată, nu o reacție la o singură pană.</p>

<p>În schimb, dacă ai avut pene frecvente pe trasee cu resturi metalice, dacă nu poți verifica regulat presiunea sau dacă o oprire neplanificată îți afectează munca, avantajul unei anvelope fără aer este ușor de înțeles. Nu mai transporți cameră, pompă și leviere pentru situații de urgență și nu mai cauți o vulcanizare în mijlocul traseului. Economisești timp și reduci o sursă comună de imobilizare. Acest beneficiu practic este motivul pentru care un cauciuc plin 9×3.0-5.5 poate fi o alegere bună chiar dacă nu este cea mai moale opțiune disponibilă.</p>

<p>Aspectul profilului poate sugera utilizare pe teren accidentat, dar recomandarea noastră rămâne realistă: oraș, asfalt variabil, alei și drumuri cu denivelări moderate, la viteze adaptate. O trotinetă cu roți de 9 inch are limite fizice în fața gropilor, rădăcinilor, noroiului adânc și pietrelor mari. Blocurile de cauciuc nu măresc diametrul roții și nu înlocuiesc tehnica de conducere. Dacă traseul principal este off-road, discută configurația completă — suspensie, frâne, protecții și anvelopă — nu doar desenul benzii de rulare.</p>

<p>Pentru verificarea vizuală, caută marcajul 9×3.0-5.5 pe flanc și compară forma canalelor interioare cu fotografiile produsului. Imaginea cu măsurători arată aproximativ 215 mm la exterior, 75 mm lățime, 48 mm în zona canalului și deschidere interioară în intervalul 125–138 mm, în funcție de punctul măsurat. Măsurătorile fotografice pot avea mici abateri, iar cauciucul este un material elastic, de aceea nu trebuie folosite singure ca șablon de montaj. Ele sunt un filtru suplimentar care te ajută să depistezi rapid o diferență evidentă.</p>

<p>Dacă produsul este temporar fără stoc, poți păstra pagina sau solicita o alternativă, dar alternativa trebuie verificată după aceleași criterii. Nu înlocui automat 9×3.0-5.5 cu 9×3, cu 8.5×3 sau cu o altă anvelopă descrisă simplu „pentru G2 Pro”. O diferență aparent mică în marcaj poate însemna altă jantă. Echipa G‑Trots poate compara produsele disponibile și îți poate spune dacă există o opțiune plină, tubeless sau pneumatică potrivită pentru revizia ta.</p>

<p><strong>Pe scurt, acest model se adresează utilizatorului care pune pe primul loc eliminarea penelor.</strong> Primești o anvelopă solidă AMITOR, neagră, cu dimensiunea marcată 9×3.0-5.5, profil mixt și structură interioară elastică. Compatibilitatea vizată este KuKirin G2 Pro 2024 echipat cu janta corespunzătoare, nu orice trotinetă care poartă numele G2 Pro. Rularea va fi mai fermă decât la un cauciuc cu aer, iar montajul necesită atenție și unelte potrivite. Verificarea și montajul pot fi solicitate în service-ul G‑Trots.</p>

<p>O comandă bună începe cu date exacte: model, an, marcaj, fotografii și, dacă este posibil, măsurători. O montare bună se termină cu verificarea centrării, a frânei, a rulmenților și a spațiului din jurul anvelopei. Dacă aceste două etape sunt respectate, cauciucul plin 9×3.0-5.5 poate elimina una dintre cele mai frecvente probleme ale utilizării zilnice — pana — și poate oferi o experiență mai previzibilă pentru cei care acceptă compromisul de confort. Pentru nelămuriri, trimite echipei G‑Trots imaginile roții înainte de comandă și cere confirmarea compatibilității sau o programare pentru montaj.</p>
HTML,
    'specifications' => [
        ['group' => 'Construcție', 'label' => 'Tip anvelopă', 'value' => 'Cauciuc plin, fără cameră și fără aer'],
        ['group' => 'Construcție', 'label' => 'Structură interioară', 'value' => 'Canale elastice longitudinale pentru reducerea rigidității față de un cauciuc complet compact'],
        ['group' => 'Construcție', 'label' => 'Profil', 'value' => 'Profil mixt cu blocuri pronunțate pe centru și umeri'],
        ['group' => 'Construcție', 'label' => 'Culoare', 'value' => 'Negru'],
        ['group' => 'Dimensiuni', 'label' => 'Marcaj anvelopă', 'value' => '9×3.0-5.5'],
        ['group' => 'Dimensiuni', 'label' => 'Diametru exterior măsurat în imagine', 'value' => 'Aproximativ 215 mm'],
        ['group' => 'Dimensiuni', 'label' => 'Lățime totală măsurată în imagine', 'value' => 'Aproximativ 75 mm'],
        ['group' => 'Dimensiuni', 'label' => 'Deschidere interioară măsurată în imagine', 'value' => 'Aproximativ 125–138 mm, în funcție de punctul de măsurare'],
        ['group' => 'Dimensiuni', 'label' => 'Lățime canal interior măsurată în imagine', 'value' => 'Aproximativ 48 mm'],
        ['group' => 'Compatibilitate', 'label' => 'Model vizat', 'value' => 'KuKirin G2 Pro 2024 cu jantă pentru 9×3.0-5.5'],
        ['group' => 'Compatibilitate', 'label' => 'Verificare obligatorie', 'value' => 'Marcajul anvelopei, anul/revizia, janta și spațiul din jurul roții trebuie confirmate înainte de montaj'],
        ['group' => 'Utilizare', 'label' => 'Avantaj principal', 'value' => 'Elimină penele și verificarea presiunii deoarece nu folosește aer'],
        ['group' => 'Utilizare', 'label' => 'Confort', 'value' => 'Rulare mai fermă decât la o anvelopă pneumatică; senzația depinde de suspensie și traseu'],
        ['group' => 'Montaj', 'label' => 'Recomandare', 'value' => 'Montaj profesional și verificarea centrării, frânei, rulmenților și cablului motorului'],
        ['group' => 'Identificare', 'label' => 'Producător', 'value' => 'AMITOR'],
        ['group' => 'Identificare', 'label' => 'Cod produs / furnizor', 'value' => 'SE-EWF897'],
        ['group' => 'Identificare', 'label' => 'EAN', 'value' => '8435764446733'],
    ],
    'questions' => [
        ['question' => 'Cu acest cauciuc mai pot face pană?', 'answer' => 'Nu în sensul clasic: anvelopa este plină, nu are cameră și nu conține aer care să se piardă printr-o înțepătură sau prin valvă. Totuși, cauciucul se poate uza, tăia sau deforma, iar o lovitură puternică poate afecta janta ori rulmenții. Avantajul este eliminarea penelor, nu eliminarea tuturor problemelor posibile ale roții.'],
        ['question' => 'Se potrivește sigur pe orice KuKirin G2 Pro?', 'answer' => 'Nu. Compatibilitatea vizată este KuKirin G2 Pro 2024 echipat cu jantă pentru 9×3.0-5.5. Există și alte revizii sau configurații asociate numelui G2 Pro. Înainte de comandă, verifică marcajul anvelopei actuale și trimite-ne fotografii cu roata și janta; G‑Trots îți poate confirma varianta corectă.'],
        ['question' => 'Este mai tare decât cauciucul cu aer?', 'answer' => 'Da, în mod normal rularea este mai fermă deoarece lipsește perna de aer. Canalele elastice din interior ajută materialul să se deformeze mai mult decât un cauciuc complet compact, însă nu oferă același confort ca o anvelopă pneumatică. Diferența resimțită depinde mult de suspensie, viteză, greutatea utilizatorului și calitatea asfaltului.'],
        ['question' => 'Pot solicita montajul la G‑Trots?', 'answer' => 'Da. G‑Trots este specializat în service pentru trotinete electrice și poți solicita verificarea compatibilității și montajul. La programare, spune modelul, anul, dimensiunea actuală și dacă roata include motorul. După montare verificăm așezarea anvelopei, centrul roții, frâna, rulmenții, cablul motorului și spațiul față de aripă.'],
        ['question' => 'Îl pot monta singur acasă?', 'answer' => 'Este posibil doar dacă ai experiență, uneltele potrivite și cunoști metoda corectă pentru janta ta. Un cauciuc plin este greu de întins, iar levierele nepotrivite sau încălzirea excesivă pot deteriora anvelopa, janta ori cablul motorului. Pentru majoritatea utilizatorilor recomandăm montajul în service, mai ales când anvelopa se montează pe roata motorizată.'],
        ['question' => 'Este bun și pe ploaie sau pe drum neasfaltat?', 'answer' => 'Profilul cu blocuri este potrivit pentru asfalt urban, pavele și porțiuni ocazionale cu suprafață mai puțin uniformă. Nu îl prezentăm însă drept anvelopă profesională de off-road și nu există aderență garantată pe ud. Redu viteza pe marcaje, metal, frunze, nisip sau piatră umedă și evită accelerațiile ori frânările bruște.'],
        ['question' => 'Cum verific dimensiunea de 5,5 inch dacă marcajul vechi nu se mai vede?', 'answer' => 'Fotografiază roata din lateral, zona jantei și flancul anvelopei, apoi măsoară diametrul și lățimea fără să demontezi componentele în nesiguranță. Imaginile acestui produs arată aproximativ 215 mm diametru exterior, 75 mm lățime și o deschidere interioară de circa 125–138 mm. Măsurătorile sunt orientative; confirmarea se face după jantă și revizia trotinetei.'],
        ['question' => 'Merită să aleg plin în loc de tubeless sau cu cameră?', 'answer' => 'Alege plin dacă prioritatea este să elimini penele și verificarea presiunii, iar un mers mai ferm este acceptabil. Alege pneumatic sau tubeless dacă pui pe primul loc confortul și aderența oferite de perna de aer și accepți întreținerea presiunii. Pentru trasee foarte denivelate, discută configurația cu service-ul înainte de conversie.'],
    ],
    'compatibility_names' => ['KuKirin'],
    'image_alt_texts' => [
        'Cauciuc plin AMITOR 9×3.0-5.5 pentru KuKirin G2 Pro 2024 – vedere laterală',
        'Profil mixt cu blocuri al cauciucului plin AMITOR 9×3.0-5.5',
        'Flanc și structură interioară elastică pentru anvelopa solidă 9×3.0-5.5',
        'Dimensiuni cauciuc plin 9×3.0-5.5: 215 mm diametru și 75 mm lățime',
    ],
    'research_sources' => [
        ['label' => 'Fișa produsului și imaginile furnizorului Boomag', 'url' => 'https://www.boomag.ro/cauciuc-plin-trotineta-electrica-9x3-5-5.html'],
        ['label' => 'Listare AMITOR cu același EAN și aceeași dimensiune', 'url' => 'https://www.decathlon.es/es/p/mp/rueda-maciza-9x3-5-5-linea-negra-amitor/e877dc05-9275-4b91-8219-5808974eb182/c1c14c1'],
        ['label' => 'Fișă tehnică și compatibilitate KuKirin G2 Pro 2024 pentru 9x3-5.5', 'url' => 'https://elektromos-roller-kerekpar-motor.hu/en/spd/250821A001/Kukirin-G2-Pro-2024-solid-tire-V3-9x3-5-5'],
        ['label' => 'Ghid de verificare a dimensiunilor anvelopelor pentru trotinete', 'url' => 'https://www.myscooterparts.com.au/blog/our-blog/how-to-find-the-right-tyre-size-for-your-electric/'],
    ],
];
