import {normalize,tokens,damerauLevenshtein,phrase} from './normalize.mjs';
const VEHICLES=[{id:'scuter electric',terms:['scuter electric','scuter','moped electric','moped','motocicleta electrica','citycoco','scooter electric cu sa']},{id:'trotinetă electrică',terms:['trotineta electrica','trotineta','scooter electric']}];
const CONTEXTS={rain:['dupa ploaie','dupa apa','ud','spalare','condens','umezeala'],cold:['la frig','iarna','rece','temperatura joasa'],hot:['la cald','dupa incalzire','se incinge','vara'],uphill:['la urcare','in panta','deal'],bumps:['denivelari','gropi','pavele','vibratii'],load:['sub sarcina','cand accelerez','acceleratie maxima','cu utilizatorul'],storage:['dupa depozitare','stat mult','nefolosita'],impact:['dupa cazatura','dupa impact','lovitura'],overnight:['peste noapte','dupa stationare'],speed:['la viteza','viteza mare']};
const STOP=new Set(['la','in','pe','cu','si','sau','de','din','dupa','cand','care','este','se','nu','mai','un','o','pentru','aproximativ','vehiculul','trotineta','scuterul','electric','electrica']);
const STEM={motorul:'motor',bateria:'baterie',incarcatorul:'incarcator',incarcarea:'incarcare',anvelopa:'anvelopa',roata:'roata',frana:'frana',displayul:'display',bordul:'bord',opreste:'oprire',incarca:'incarcare',porneste:'pornire',bazaie:'bazait',pierde:'pierdere',smuceste:'smucit',vibreaza:'vibratie',incinge:'incalzire'};
function stem(t){t=normalize(t);return STEM[t]||t.replace(/(ului|elor|ilor|ul|ele|ii)$/,'').replace(/(este|eaza)$/,'');}
function stemTokens(s){return [...new Set(tokens(s).map(stem).filter(t=>t.length>2&&!STOP.has(t)))];}
export class QueryParser{
 constructor(models,symptoms,entity){this.models=models.models||models;this.symptoms=symptoms.symptoms||symptoms;this.entity=entity;this.modelAliases=Object.keys(entity.model_aliases||{}).sort((a,b)=>b.length-a.length);this.symptomAliases=Object.keys(entity.symptom_aliases||{}).sort((a,b)=>b.length-a.length);this.brands=Object.keys(entity.brands||{}).sort((a,b)=>b.length-a.length);this.symptomVectors=this.symptoms.map(s=>({id:s.id,tokens:new Set(stemTokens([s.symptom,...(s.aliases||[])].join(' '))),family:s.family,aliases:s.aliases||[]}));this.modelVectors=this.models.map(m=>({id:m.id,tokens:new Set(tokens([m.brand,m.model,...(m.aliases||[])].join(' ')).filter(t=>t.length>1)),label:normalize(`${m.brand} ${m.model}`)}));}
 parse(raw){const q=normalize(raw),qt=tokens(q);let vehicle='';for(const v of VEHICLES)if(v.terms.some(t=>phrase(q,t))){vehicle=v.id;break;}
  let models=[];for(const al of this.modelAliases){if(al.length<4&&!/\d/.test(al))continue;if(phrase(q,al))for(const id of this.entity.model_aliases[al]||[]){const m=this.models[id];models.push({id,alias:al,label:m?normalize(`${m.brand} ${m.model}`):al,exact:true,similarity:1});}}
  if(models.length){const max=Math.max(...models.map(x=>x.alias.length));models=models.filter(x=>x.alias.length===max);}else{const qset=new Set(qt),overlap=[];for(const m of this.modelVectors){let hit=0;for(const t of m.tokens)if(qset.has(t))hit++;const voltage=[...m.tokens].find(t=>/^\d{2,3}v$/.test(t));if(voltage&&!qset.has(voltage))continue;const score=hit/Math.max(1,Math.min(m.tokens.size,qset.size));if(hit>=2&&score>=.42)overlap.push({id:m.id,alias:m.label,label:m.label,exact:false,similarity:score});}models=overlap.sort((a,b)=>b.similarity-a.similarity).slice(0,5);if(!models.length){const chunks=[];for(let n=Math.min(6,qt.length);n>=1;n--)for(let i=0;i+n<=qt.length;i++)chunks.push(qt.slice(i,i+n).join(' '));const best=[];for(const chunk of chunks){if(chunk.length<4)continue;for(const al of this.modelAliases){if(Math.abs(chunk.length-al.length)>4)continue;const max=Math.max(1,Math.floor(al.length*.18)),d=damerauLevenshtein(chunk,al,max);if(d<=max){const id=(this.entity.model_aliases[al]||[])[0],m=this.models[id];best.push({id,alias:al,label:m?normalize(`${m.brand} ${m.model}`):al,exact:false,similarity:1-d/Math.max(chunk.length,al.length)});}}}models=best.sort((a,b)=>b.similarity-a.similarity).slice(0,5);}}
  const ms=new Set();models=models.filter(x=>x.id!==undefined&&!ms.has(x.id)&&ms.add(x.id));let brand='';for(const b of this.brands)if(phrase(q,b)){brand=b;break;}
  let symptoms=[];for(const al of this.symptomAliases)if(phrase(q,al))for(const id of this.entity.symptom_aliases[al]||[])symptoms.push({id,alias:al,exact:true,score:1});
  const entityTerms=new Set([brand,...models.flatMap(m=>tokens(m.alias))].filter(Boolean)),qst=new Set(stemTokens(q).filter(t=>!entityTerms.has(t)));
  if(qst.size)for(const s of this.symptomVectors){let hit=0;for(const t of qst)if(s.tokens.has(t))hit++;const score=hit/Math.sqrt(Math.max(1,qst.size*s.tokens.size));if(hit>=2&&score>=.28)symptoms.push({id:s.id,alias:'semantic-token-overlap',exact:false,score,family:s.family});}
  const percentageMatch=(String(raw).match(/\b(\d{1,3})\s*%/)||[])[1],voltageMatch=(q.match(/\b(\d{2,3})\s*v\b/)||[])[1],errorMatch=(q.match(/\b(?:eroare|error|cod)\s*([a-z]?\d{1,4})\b/)||[])[1];
  const direct=[];if(/\b(opreste|stinge)\b/.test(q)&&(percentageMatch||/\b(sub|jumatate)\b/.test(q)))direct.push('se-opreste-sub-40-baterie','v5-se-opreste-sub-40','v5-se-stinge-la-jumatatea-bateriei');if(/\bnu (se )?incarca\b/.test(q))direct.push('incarcator-verde-nu-incarca');if(/frana hidraulica/.test(q)&&/pierde.*lichid|lichid.*pierde/.test(q))direct.push('frana-hidraulica-pierde-lichid');if(/motor/.test(q)&&/bazai|bâzâi|zgomot/.test(q))direct.push('motor-bazaie-nu-trage','motor-bazaie-roata-smuceste','v5-motor-bazaie-fara-rotatie');if(/\bnu (mai )?porneste\b/.test(q))direct.push('nu-porneste-dupa-depozitare','nu-porneste-dupa-ploaie');for(const id of direct)symptoms.push({id,alias:'direct-intent-rule',exact:true,score:1.2});
  const ss=new Map();for(const x of symptoms){const old=ss.get(x.id);if(!old||x.score>old.score)ss.set(x.id,x);}symptoms=[...ss.values()].sort((a,b)=>b.score-a.score).slice(0,8);
  const contexts=[];for(const [id,terms] of Object.entries(CONTEXTS))if(terms.some(t=>phrase(q,t)))contexts.push(id);
  return{raw,normalized:q,tokens:qt,vehicle,brand,models,symptoms,contexts,percentage:percentageMatch?Number(percentageMatch):null,voltage:voltageMatch?Number(voltageMatch):null,error:errorMatch||null};}
}
