import {normalize,tokens} from './normalize.mjs';
const FILLER=new Set('la in pe cu si sau de din dupa cand se nu mai un o'.split(' '));
const COMPONENTS=new Set('display ecran bord frana motor baterie acumulator incarcator controller acceleratie roata anvelopa camera furca suspensie far stop semnalizare cablu mufa maneta disc etrier'.split(' '));
const CONTEXT_TERMS={rain:['ploaie','apa','ud','spalare','condens','umezeala'],cold:['frig','iarna','rece','temperatura joasa'],hot:['cald','incalz','incinge','temperatura'],uphill:['urcare','panta','deal'],bumps:['denivelari','gropi','pavele','vibratii'],load:['sarcina','accelerez','acceleratie maxima'],storage:['depozitare','stat mult','nefolosita'],impact:['cazatura','impact','lovitura'],overnight:['peste noapte','stationare'],speed:['viteza','viteza mare']};
export function rerank(fused,docs,parsed,config){const w=config.weights||{},q=parsed.normalized,qTokens=new Set(parsed.tokens||[]),parsedModelLabels=(parsed.models||[]).map(m=>normalize(m.label||m.alias));return fused.map(x=>{const d=docs[x.id];if(!d)return null;let s=x.score*1000;const reasons=[...x.sources],title=normalize(d.title),brand=normalize(d.brand||''),model=normalize([d.brand,d.model].filter(Boolean).join(' ')),sym=normalize(d.symptom),family=normalize(d.family),ctx=normalize([...(d.contexts||[]),d.context].filter(Boolean).join(' ')),vehicle=normalize(d.vehicle||d.vehicle_type||'');if(q&&title===q){s+=120;reasons.push('title-exact');}else if(q&&title.includes(q)){s+=w.title_phrase||30;reasons.push('title-phrase');}
 if(parsed.vehicle){if(vehicle.includes(normalize(parsed.vehicle))){s+=w.vehicle_match||24;reasons.push('vehicle-match');}else{s+=w.vehicle_mismatch||-75;reasons.push('vehicle-mismatch');}}
 if(parsed.brand){if(brand===parsed.brand){s+=w.exact_brand||22;reasons.push('brand-match');}else if(brand)s-=25;}
 if(!parsedModelLabels.length&&!parsed.brand&&!parsed.voltage){if(model){s-=14;reasons.push('generic-query-model-penalty');}else{s+=18;reasons.push('generic-query-general-boost');}}
 if(parsedModelLabels.length){const match=Boolean(model)&&parsedModelLabels.some(m=>m&&(model===m||model.includes(m)||m.includes(model)));if(match){const exact=parsed.models.some(m=>m.exact);s+=exact?(w.exact_model||72):(w.fuzzy_model||38);reasons.push(exact?'model-exact':'model-fuzzy');}else{s+=model?(w.model_mismatch||-90):-10;reasons.push(model?'model-mismatch':'model-missing');}}
 if(parsed.symptoms?.some(z=>z.id===d.symptom_id)){s+=w.exact_symptom||58;reasons.push('symptom-exact');}else if(parsed.symptoms?.some(z=>normalize(z.family||'')===family&&family)){s+=w.same_family||18;reasons.push('symptom-family');}
 let overlap=0;for(const t of qTokens){if(title.includes(t))overlap+=2.4;else if(sym.includes(t))overlap+=1.7;else if(ctx.includes(t))overlap+=1;}s+=overlap*(w.context_token||4.2);const meaningful=(parsed.tokens||[]).filter(t=>!FILLER.has(t));for(let i=0;i<meaningful.length-1;i++){const pair=`${meaningful[i]} ${meaningful[i+1]}`;if(title.includes(pair)||sym.includes(pair))s+=18;}
 for(const c of parsed.contexts||[]){const terms=CONTEXT_TERMS[c]||[c],has=(hay,t)=>{const nt=normalize(t);return nt.length<=3?(` ${hay} `).includes(` ${nt} `):hay.includes(nt);},matched=terms.some(t=>has(title,t)||has(sym,t)||has(ctx,t));if(matched){s+=34;reasons.push(`context-${c}`);}else{s-=22;}}if(parsed.percentage!==null){const n=String(parsed.percentage);if(title.includes(n)||ctx.includes(n)||sym.includes(n)){s+=(w.percentage||12)*2.4;reasons.push('percentage-match');}else if(/\b(80|90|100|50)\b/.test(title))s-=18;}if(parsed.voltage!==null&&(title.includes(String(parsed.voltage))||model.includes(String(parsed.voltage))))s+=w.voltage||15;if(parsed.error&&(title.includes(parsed.error)||sym.includes(parsed.error)))s+=w.error_code||45;const problemTokens=(parsed.tokens||[]).filter(t=>!FILLER.has(t)&&!parsedModelLabels.some(m=>m.includes(t))&&t!==parsed.brand);let problemHits=0;for(const t of problemTokens)if(title.includes(t)||sym.includes(t))problemHits++;if(problemTokens.length&&problemHits===problemTokens.length){s+=120;reasons.push('all-problem-tokens');}else if(problemHits>=2)s+=problemHits*7;const componentHits=problemTokens.filter(t=>COMPONENTS.has(t)&&(title.includes(t)||sym.includes(t))).length;if(componentHits){s+=componentHits*32;reasons.push('component-match');}if(parsedModelLabels.length&&problemTokens.length>=2&&problemHits<Math.ceil(problemTokens.length*.5)){s-=problemHits?85:125;reasons.push('model-with-wrong-problem');}s+=(d.quality||0)*(w.quality||5);return{...x,score:s,doc:d,reasons:[...new Set(reasons)]};}).filter(Boolean).sort((a,b)=>b.score-a.score);}
export function diversify(rows,limit=12){const out=[],seen=new Set();for(const r of rows){const key=`${r.doc.model}|${r.doc.symptom_id}|${(r.doc.contexts||[]).join(',')}`;if(seen.has(key)&&out.length>=4)continue;seen.add(key);out.push(r);if(out.length>=limit)break;}return out;}
