import {getJSON,getBuffer} from './binary-loader.mjs';import {inflateTable} from './compact.mjs';import {InstantSearch} from './instant-search.mjs';import {QueryParser} from './query-parser.mjs';import {BinaryBM25} from './bm25-binary.mjs';import {TrigramSearch} from './trigram-search.mjs';import {LocalSemanticSearch} from './semantic-local.mjs';import {reciprocalRankFusion} from './rrf.mjs';import {rerank,diversify} from './reranker.mjs';import {buildDiagnosis} from './diagnostic.mjs';import {normalize} from './normalize.mjs';import {NeuralRerankerProvider} from './neural-reranker-provider.mjs';
export class GTrotsSearchEngine{
 constructor({baseUrl='/',neuralRerankerEndpoint=''}={}){this.base=new URL(baseUrl,globalThis.location?.origin||'http://localhost');this.phase='empty';this.neural=new NeuralRerankerProvider({endpoint:neuralRerankerEndpoint});}
 u(p){return new URL(p,this.base);}
 async initInstant(onProgress=()=>{}){this.config=await getJSON(this.u('search/data/config.json'));const a=this.config.assets||{};const [payload,meta,postings]=await Promise.all([getJSON(this.u(a.instant||'search/data/instant-core.json')),getJSON(this.u(a.instant_postings_meta||'search/data/instant-postings-v61-meta.json')),getBuffer(this.u(a.instant_postings_bin||'search/data/instant-postings-v61.bin'))]);this.instantDocs=inflateTable(payload);this.instant=new InstantSearch(this.instantDocs,meta,postings);this.phase='instant';onProgress({phase:'instant',count:this.instantDocs.length,indexedTokens:meta.tokens?.length||0});return this;} async initFull(onProgress=()=>{}){const a=this.config.assets;const [docPayload,bmMeta,bmPost,dl,triMeta,triPost,triCounts,semMeta,semVec,entity,models,symptoms]=await Promise.all([getJSON(this.u(a.docs)),getJSON(this.u(a.bm25_meta)),getBuffer(this.u(a.bm25_postings)),getBuffer(this.u(a.doc_lengths)),getJSON(this.u(a.trigram_meta)),getBuffer(this.u(a.trigram_postings)),getBuffer(this.u(a.trigram_counts)),getJSON(this.u(a.semantic_meta)),getBuffer(this.u(a.semantic_vectors)),getJSON(this.u(a.entity)),getJSON(this.u(a.models)),getJSON(this.u(a.symptoms))]);this.docs=inflateTable(docPayload);this.bm25=new BinaryBM25(bmMeta,bmPost,dl);this.trigram=new TrigramSearch(triMeta,triPost,triCounts);this.semantic=new LocalSemanticSearch(semMeta,semVec);this.entity=entity;this.models=models.models||models;this.symptoms=symptoms.symptoms||symptoms;this.parser=new QueryParser(models,symptoms,entity);this.phase='full';onProgress({phase:'full',count:this.docs.length});return this;}
 instantSearch(query,limit=10){return this.instant?.search(query,limit)||[];}
 entityRank(parsed){const out=[],seen=new Set(),add=(ids,base)=>{for(let pos=0;pos<(ids||[]).length;pos++){const id=ids[pos];if(!seen.has(id)){seen.add(id);out.push({id,score:base-pos*.0001});}}};for(const m of parsed.models||[]){const model=this.models[m.id];if(model)add(this.entity.model_docs[normalize(`${model.brand} ${model.model}`)],12);}if(parsed.brand)add(this.entity.brand_docs[parsed.brand],6);for(const s of parsed.symptoms||[])add(this.entity.symptom_docs[s.id],11);return out;}
 async search(query,{limit=12,neural=false}={}){if(!query||query.trim().length<2)return{phase:this.phase,query,results:[]};if(this.phase!=='full')return{phase:this.phase,query,results:this.instantSearch(query,limit)};const parsed=this.parser.parse(query),lex=this.bm25.search(query,this.config.candidate_limit),ent=this.entityRank(parsed),exactModel=parsed.models?.some(m=>m.exact),strongSymptom=parsed.symptoms?.some(s=>s.exact),fuzzy=exactModel?[]:this.trigram.search(query,this.config.candidate_limit),sem=(exactModel&&strongSymptom)?[]:this.semantic.search(query,parsed,this.config.candidate_limit),fused=reciprocalRankFusion([{name:'bm25',items:lex,weight:1.08},{name:'entities',items:ent,weight:1.28},{name:'trigram',items:fuzzy,weight:.88},{name:'semantic',items:sem,weight:.94}],this.config.rrf_k,this.config.rerank_limit*4);let ranked=rerank(fused,this.docs,parsed,this.config);ranked=diversify(ranked,Math.max(limit,24));if(neural&&this.neural.enabled){const nr=await this.neural.rerank(query,ranked.slice(0,30));if(nr?.scores){const map=new Map(nr.scores.map(x=>[x.id,x.score]));ranked.sort((a,b)=>(map.get(b.doc.id)||0)-(map.get(a.doc.id)||0)||b.score-a.score);}}
 const final=ranked.slice(0,limit);return{phase:'full',query_understanding:parsed,diagnosis:buildDiagnosis(parsed,final),results:final.map((r,i)=>({rank:i+1,score:Number(r.score.toFixed(4)),reasons:r.reasons,...r.doc}))};}
}
