import React, { useCallback, useEffect, useMemo, useState } from 'react';
import { ActivityIndicator, Alert, Image, Linking, ScrollView, StyleSheet, Switch, Text, TouchableOpacity, View } from 'react-native';
import { Check, CloudUpload, FileCheck2, KeyRound, RefreshCw, Save, ShieldCheck, Unplug, Zap } from 'lucide-react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { Colors } from '@/constants/colors';
import { useAuth } from '@/contexts/AuthContext';
import { shopApi, ShopSpvConnection, ShopSpvDiagnostics, ShopSpvMode, ShopSpvSettings } from '@/services/shopApi';

const modeOptions: { value: ShopSpvMode; title: string; hint: string }[] = [
  { value: 'manual', title: 'Manual', hint: 'Trimiți din factura aleasă' },
  { value: 'on_issue', title: 'La emitere', hint: 'Intră imediat în coada ANAF' },
  { value: 'delayed', title: 'Programat', hint: 'După 1–5 zile lucrătoare' },
];

function dateTime(value?: string | null) {
  if (!value) return '—';
  const date = new Date(value.replace(' ', 'T'));
  return Number.isNaN(date.getTime()) ? value : date.toLocaleString('ro-RO', { dateStyle: 'medium', timeStyle: 'short' });
}

function AutomationCard({ title, subtitle, mode, delay, onMode, onDelay, color }: { title: string; subtitle: string; mode: ShopSpvMode; delay: number; onMode: (value: ShopSpvMode) => void; onDelay: (value: number) => void; color: string }) {
  return <View style={[styles.automationCard, { borderColor: `${color}55` }]}>
    <View style={styles.automationHead}><View style={[styles.automationIcon, { backgroundColor: `${color}18` }]}><CloudUpload size={21} color={color} /></View><View style={styles.flex}><Text style={styles.automationTitle}>{title}</Text><Text style={styles.automationSubtitle}>{subtitle}</Text></View></View>
    <View style={styles.modeList}>{modeOptions.map((option) => <TouchableOpacity key={option.value} activeOpacity={0.72} style={[styles.modeOption, mode === option.value && { borderColor: color, backgroundColor: `${color}16` }]} onPress={() => onMode(option.value)}><View style={[styles.radio, mode === option.value && { borderColor: color, backgroundColor: color }]}>{mode === option.value ? <Check size={11} color="#141216" strokeWidth={3} /> : null}</View><Text numberOfLines={1} style={[styles.modeTitle, mode === option.value && { color }]}>{option.title}</Text></TouchableOpacity>)}</View>
    <Text style={styles.selectedModeHint}>{modeOptions.find((option) => option.value === mode)?.hint}</Text>
    {mode === 'delayed' ? <View style={styles.delayBlock}><Text style={styles.delayLabel}>TRIMITE DUPĂ</Text><View style={styles.delayList}>{[1, 2, 3, 4, 5].map((day) => <TouchableOpacity key={day} style={[styles.delayButton, delay === day && { borderColor: color, backgroundColor: color }]} onPress={() => onDelay(day)}><Text style={[styles.delayText, delay === day && styles.delayTextActive]}>{day}</Text></TouchableOpacity>)}</View><Text style={styles.delayHint}>zile lucrătoare de la emitere</Text></View> : null}
  </View>;
}

export default function ShopSpvManager() {
  const { token } = useAuth();
  const insets = useSafeAreaInsets();
  const [connection, setConnection] = useState<ShopSpvConnection | null>(null);
  const [draft, setDraft] = useState<ShopSpvSettings | null>(null);
  const [loading, setLoading] = useState(true);
  const [busy, setBusy] = useState('');
  const [error, setError] = useState('');
  const [waitingForOAuth, setWaitingForOAuth] = useState(false);
  const [diagnostics, setDiagnostics] = useState<ShopSpvDiagnostics | null>(null);

  const load = useCallback(async (quiet = false) => {
    if (!token) return;
    if (!quiet) setLoading(true);
    try {
      const next = await shopApi.getSpvConnection(token);
      setConnection(next);
      if (next.settings) setDraft(next.settings);
      setError('');
      if (next.connected) setWaitingForOAuth(false);
    } catch (loadError) { setError(loadError instanceof Error ? loadError.message : 'Conexiunea SPV nu a putut fi verificată.'); }
    finally { if (!quiet) setLoading(false); }
  }, [token]);

  useEffect(() => { void load(); }, [load]);
  useEffect(() => {
    if (!waitingForOAuth) return;
    const timer = setInterval(() => void load(true), 3000);
    return () => clearInterval(timer);
  }, [load, waitingForOAuth]);

  const changed = useMemo(() => Boolean(connection?.settings && draft && JSON.stringify(connection.settings) !== JSON.stringify(draft)), [connection?.settings, draft]);
  const connect = async () => {
    if (!token || busy) return;
    setBusy('connect');
    try {
      const result = await shopApi.beginSpvOAuth(token);
      setWaitingForOAuth(true);
      await Linking.openURL(result.authorization_url);
    } catch (connectError) { Alert.alert('Conectarea nu a pornit', connectError instanceof Error ? connectError.message : 'Încearcă din nou.'); }
    finally { setBusy(''); }
  };
  const save = async () => {
    if (!token || !draft || busy) return;
    setBusy('save');
    try { const next = await shopApi.updateSpvSettings(token, draft); setConnection(next); if (next.settings) setDraft(next.settings); Alert.alert('Automatizări salvate', 'Coada tuturor facturilor netrimise a fost recalculată după noile reguli.'); }
    catch (saveError) { Alert.alert('Setările nu au fost salvate', saveError instanceof Error ? saveError.message : 'Încearcă din nou.'); }
    finally { setBusy(''); }
  };
  const test = async () => {
    if (!token || busy) return;
    setBusy('test');
    try { const next = await shopApi.testSpvConnection(token); setConnection(next); Alert.alert('Conexiune validă', 'ANAF a acceptat tokenul OAuth al firmei.'); }
    catch (testError) { Alert.alert('Test nereușit', testError instanceof Error ? testError.message : 'ANAF nu a răspuns.'); }
    finally { setBusy(''); }
  };
  const runDiagnostics = async () => {
    if (!token || busy || connection?.environment !== 'test') return;
    setBusy('diagnostics');
    setDiagnostics(null);
    try {
      let result = await shopApi.runSpvDiagnostics(token);
      setDiagnostics(result);
      for (let attempt = 0; attempt < 10 && result.documents.some((document) => !document.terminal); attempt += 1) {
        await new Promise((resolve) => setTimeout(resolve, 2500));
        const next = await shopApi.pollSpvDiagnostics(token, result.documents.map((document) => document.upload_index).filter(Boolean));
        const updates = new Map(next.documents.map((document) => [document.upload_index, document]));
        result = { ...result, documents: result.documents.map((document) => ({ ...document, ...(updates.get(document.upload_index) || {}) })) };
        setDiagnostics(result);
      }
      const rejected = result.documents.some((document) => document.state === 'rejected');
      const pending = result.documents.some((document) => !document.terminal);
      Alert.alert(rejected ? 'ANAF Test a respins un document' : pending ? 'Testul continuă în ANAF' : 'Flux SPV confirmat', rejected ? 'Deschide rezultatele de mai jos pentru identificatorul respins.' : pending ? 'Documentele sunt încărcate și pot fi reverificate.' : 'Invoice 380 și CreditNote 381 au fost validate, încărcate și acceptate în mediul Test.');
    } catch (testError) { Alert.alert('Testul complet nu a reușit', testError instanceof Error ? testError.message : 'ANAF Test nu a răspuns.'); }
    finally { setBusy(''); }
  };
  const disconnect = () => Alert.alert('Deconectezi SPV?', 'Tokenurile criptate vor fi revocate și șterse de pe server.', [{ text: 'Renunță', style: 'cancel' }, { text: 'Deconectează', style: 'destructive', onPress: async () => { if (!token) return; setBusy('disconnect'); try { const next = await shopApi.disconnectSpv(token); setConnection(next); setDraft(null); } catch (disconnectError) { Alert.alert('Nu s-a putut deconecta', disconnectError instanceof Error ? disconnectError.message : 'Încearcă din nou.'); } finally { setBusy(''); } } }]);

  if (loading) return <View style={styles.loading}><ActivityIndicator color="#8AB4F8" /><Text style={styles.loadingText}>Verificăm legătura securizată cu ANAF...</Text></View>;

  return <ScrollView style={styles.screen} contentContainerStyle={[styles.content, { paddingBottom: 120 + insets.bottom }]} showsVerticalScrollIndicator={false}>
    <View style={styles.hero}><View style={styles.heroGlow} /><View style={styles.heroOrbit} /><View style={styles.heroTop}><View style={styles.logo}><Image source={require('../assets/images/anaf-ro.png')} resizeMode="contain" style={styles.logoImage} /></View><View style={[styles.statePill, connection?.connected ? styles.stateConnected : styles.stateDisconnected]}><View style={[styles.stateDot, { backgroundColor: connection?.connected ? '#6EE7B7' : '#A8C7FA' }]} /><Text style={[styles.stateText, { color: connection?.connected ? '#6EE7B7' : '#A8C7FA' }]}>{connection?.connected ? 'CONECTAT' : 'NECONECTAT'}</Text></View></View><Text style={styles.kicker}>ANAF · CONFIGURARE SECURIZATĂ</Text><Text style={styles.title}>RO e-Factura</Text><Text style={styles.heroText}>{connection?.connected ? 'Conexiunea SPV este păstrată criptat pe server și rămâne disponibilă pe toate dispozitivele autentificate.' : 'Conectează certificatul digital o singură dată, direct în pagina oficială ANAF.'}</Text><View style={styles.heroMeta}><View><ShieldCheck size={14} color="#6EE7B7" /><Text style={styles.heroMetaText}>Token criptat</Text></View><View><RefreshCw size={14} color="#A8C7FA" /><Text style={styles.heroMetaText}>Reînnoire automată</Text></View></View></View>
    {error ? <View style={styles.errorCard}><Text style={styles.errorText}>{error}</Text><TouchableOpacity onPress={() => void load()}><RefreshCw size={18} color="#FDA4AF" /></TouchableOpacity></View> : null}
    {!connection?.connected ? <View style={styles.connectCard}><View style={styles.connectIcon}><KeyRound size={25} color="#A8C7FA" /></View><Text style={styles.connectTitle}>Conectează firma la SPV</Text><Text style={styles.connectText}>{connection?.configured ? 'Vei fi redirecționat pe pagina oficială ANAF pentru alegerea certificatului. După confirmare, revino aici.' : 'Datele OAuth trebuie configurate mai întâi în zona securizată a serverului.'}</Text><TouchableOpacity disabled={!connection?.configured || Boolean(busy)} style={[styles.connectButton, (!connection?.configured || Boolean(busy)) && styles.disabled]} onPress={() => void connect()}>{busy === 'connect' ? <ActivityIndicator color="#111217" /> : <ShieldCheck size={20} color="#111217" />}<Text style={styles.connectButtonText}>{waitingForOAuth ? 'Așteptăm confirmarea ANAF' : 'Conectează SPV'}</Text></TouchableOpacity>{waitingForOAuth ? <TouchableOpacity style={styles.refreshLink} onPress={() => void load()}><RefreshCw size={16} color="#A8C7FA" /><Text style={styles.refreshText}>Am confirmat certificatul · verifică acum</Text></TouchableOpacity> : null}</View> : <>
      <View style={styles.connectionCard}><View style={styles.connectionTop}><View style={styles.connectionCheck}><ShieldCheck size={22} color="#6EE7B7" /></View><View style={styles.flex}><Text style={styles.connectionEyebrow}>CONEXIUNE VERIFICATĂ</Text><Text style={styles.connectionTitle}>Server ANAF activ</Text><Text style={styles.connectionMeta}>Certificat {connection.certificate_hint || 'verificat'} · {dateTime(connection.last_tested_at)}</Text></View></View><View style={styles.tokenGrid}><View style={styles.tokenCard}><Text style={styles.tokenLabel}>ACCESS</Text><Text style={styles.tokenValue}>Expiră</Text><Text style={styles.tokenDate}>{dateTime(connection.access_expires_at)}</Text></View><View style={styles.tokenCard}><Text style={styles.tokenLabel}>REFRESH</Text><Text style={styles.tokenValue}>Valabil până la</Text><Text style={styles.tokenDate}>{dateTime(connection.refresh_expires_at)}</Text></View></View><View style={styles.connectionActions}><TouchableOpacity disabled={Boolean(busy)} style={styles.testButton} onPress={() => void test()}><RefreshCw size={15} color="#A8C7FA" /><Text style={styles.testText}>Verifică legătura</Text></TouchableOpacity><TouchableOpacity disabled={Boolean(busy)} style={styles.disconnectButton} onPress={disconnect}><Unplug size={15} color="#FDA4AF" /><Text style={styles.disconnectText}>Deconectează</Text></TouchableOpacity></View></View>
      {connection.environment === 'test' ? <View style={styles.diagnosticsCard}><View style={styles.diagnosticsHead}><View style={styles.diagnosticsIcon}><FileCheck2 size={20} color="#A8C7FA" /></View><View style={styles.flex}><Text style={styles.diagnosticsKicker}>TEST IZOLAT · FĂRĂ EFECT FISCAL</Text><Text style={styles.diagnosticsTitle}>Verifică fluxul complet</Text><Text style={styles.diagnosticsText}>Invoice 380 + retur 381, validate și încărcate numai în sandbox.</Text></View></View>{diagnostics?.documents?.length ? <View style={styles.diagnosticsResults}>{diagnostics.documents.map((document) => <View key={document.upload_index} style={styles.diagnosticRow}><View style={[styles.diagnosticState, document.state === 'accepted' ? styles.diagnosticAccepted : document.state === 'rejected' ? styles.diagnosticRejected : null]}><Text style={styles.diagnosticStateText}>{document.state === 'accepted' ? '✓' : document.state === 'rejected' ? '!' : '…'}</Text></View><View style={styles.flex}><Text style={styles.diagnosticName}>{document.kind === 'credit_note_381' ? 'CreditNote 381' : 'Invoice 380'}</Text><Text style={styles.diagnosticMeta}>{document.state === 'accepted' ? 'Acceptat de ANAF Test' : document.state === 'rejected' ? 'Respins · verifică detaliile' : 'În procesare'}</Text></View></View>)}</View> : null}<TouchableOpacity disabled={Boolean(busy)} style={styles.diagnosticsButton} onPress={() => void runDiagnostics()}>{busy === 'diagnostics' ? <ActivityIndicator color="#F4F8FF" /> : <Zap size={16} color="#F4F8FF" />}<Text style={styles.diagnosticsButtonText}>{busy === 'diagnostics' ? 'Se verifică…' : 'Rulează testul complet'}</Text></TouchableOpacity></View> : null}
      {draft ? <><View style={styles.environmentCard}><View style={styles.sectionHead}><View><Text style={styles.sectionKicker}>MEDIU DE TRANSMITERE</Text><Text style={styles.sectionTitle}>Destinația documentelor</Text></View><View style={styles.deadlinePill}><Zap size={12} color="#FBBF24" /><Text style={styles.deadlineText}>5 zile</Text></View></View><View style={styles.environment}><TouchableOpacity style={[styles.environmentButton, draft.environment === 'test' && styles.environmentTest]} onPress={() => setDraft({ ...draft, environment: 'test' })}><Text style={[styles.environmentText, draft.environment === 'test' && styles.environmentTextActive]}>Test ANAF</Text></TouchableOpacity><TouchableOpacity style={[styles.environmentButton, draft.environment === 'production' && styles.environmentProduction]} onPress={() => setDraft({ ...draft, environment: 'production' })}><Text style={[styles.environmentText, draft.environment === 'production' && styles.environmentTextActive]}>Producție</Text></TouchableOpacity></View>{draft.environment === 'test' ? <Text style={styles.environmentHint}>Sandbox fără efect fiscal. Producția se activează numai prin alegerea ta explicită.</Text> : <Text style={[styles.environmentHint, { color: '#FCD34D' }]}>Mod Producție: documentele acceptate sunt transmise oficial în RO e-Factura.</Text>}</View>
      <View style={styles.sectionHead}><View><Text style={styles.sectionKicker}>REGULI AUTOMATE</Text><Text style={styles.sectionTitle}>Momentul transmiterii</Text></View></View>
      <AutomationCard title="Facturi emise" subtitle="Facturile pozitive din vânzări" mode={draft.invoice_mode} delay={draft.invoice_delay_days} color="#60A5FA" onMode={(invoice_mode) => setDraft({ ...draft, invoice_mode })} onDelay={(invoice_delay_days) => setDraft({ ...draft, invoice_delay_days })} />
      <AutomationCard title="Facturi de retur" subtitle="Facturi de corecție · cod 381" mode={draft.return_mode} delay={draft.return_delay_days} color="#F472B6" onMode={(return_mode) => setDraft({ ...draft, return_mode })} onDelay={(return_delay_days) => setDraft({ ...draft, return_delay_days })} />
      <View style={styles.reminderRow}><View style={styles.flex}><Text style={styles.reminderTitle}>Alerte termen legal</Text><Text style={styles.reminderText}>Notifică atunci când mai sunt cel mult 2 zile lucrătoare din termenul legal de 5 zile.</Text></View><Switch value={draft.reminders_enabled} onValueChange={(reminders_enabled) => setDraft({ ...draft, reminders_enabled })} trackColor={{ false: '#3D3941', true: '#315C49' }} thumbColor={draft.reminders_enabled ? '#6EE7B7' : '#979198'} /></View>
      <TouchableOpacity disabled={!changed || Boolean(busy)} style={[styles.saveButton, (!changed || Boolean(busy)) && styles.disabled]} onPress={() => void save()}>{busy === 'save' ? <ActivityIndicator color="#151216" /> : <Save size={19} color="#151216" />}<Text style={styles.saveText}>Salvează și recalculează coada</Text></TouchableOpacity></> : null}
    </>}
  </ScrollView>;
}

const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: Colors.bg }, content: { width: '100%', maxWidth: 760, alignSelf: 'center', gap: 12, padding: 15 }, flex: { flex: 1, minWidth: 0 }, loading: { flex: 1, alignItems: 'center', justifyContent: 'center', gap: 12, backgroundColor: Colors.bg }, loadingText: { color: Colors.textSecondary, fontFamily: 'Inter-Medium', fontSize: 11 },
  hero: { minHeight: 268, overflow: 'hidden', borderWidth: 1, borderColor: '#314A68', borderRadius: 28, padding: 20, backgroundColor: '#171F29' }, heroGlow: { position: 'absolute', left: -80, bottom: -120, width: 260, height: 220, borderRadius: 130, backgroundColor: '#2563EB12' }, heroOrbit: { width: 250, height: 250, position: 'absolute', right: -115, top: -100, borderWidth: 42, borderColor: '#A8C7FA0A', borderRadius: 125 }, heroTop: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 10 }, logo: { width: 158, height: 54, alignItems: 'center', justifyContent: 'center', overflow: 'hidden', borderRadius: 15, backgroundColor: '#FFFFFF' }, logoImage: { width: 148, height: 50 }, statePill: { flexDirection: 'row', alignItems: 'center', gap: 6, borderWidth: 1, borderRadius: 99, paddingHorizontal: 10, paddingVertical: 7 }, stateConnected: { borderColor: '#6EE7B744', backgroundColor: '#6EE7B70D' }, stateDisconnected: { borderColor: '#A8C7FA33', backgroundColor: '#A8C7FA0B' }, stateDot: { width: 7, height: 7, borderRadius: 4 }, stateText: { fontFamily: 'Inter-Bold', fontSize: 8, letterSpacing: 0.7 }, kicker: { color: '#A8C7FA', fontFamily: 'Inter-Bold', fontSize: 8, letterSpacing: 1.2, marginTop: 22 }, title: { color: '#FFF8F2', fontFamily: 'Inter-Bold', fontSize: 32, marginTop: 6 }, heroText: { maxWidth: 570, color: '#B9C0CA', fontFamily: 'Inter-Regular', fontSize: 10.5, lineHeight: 17, marginTop: 8 }, heroMeta: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginTop: 17 }, heroMetaText: { color: '#C8D2E0', fontFamily: 'Inter-SemiBold', fontSize: 8.5 },
  errorCard: { minHeight: 54, flexDirection: 'row', alignItems: 'center', gap: 10, borderWidth: 1, borderColor: '#7F3344', borderRadius: 18, padding: 14, backgroundColor: '#321A21' }, errorText: { flex: 1, color: '#FDA4AF', fontFamily: 'Inter-Medium', fontSize: 10, lineHeight: 15 }, connectCard: { alignItems: 'center', borderWidth: 1, borderColor: '#3D4555', borderRadius: 26, padding: 23, backgroundColor: '#1B1C21' }, connectIcon: { width: 58, height: 58, alignItems: 'center', justifyContent: 'center', borderRadius: 19, backgroundColor: '#A8C7FA14' }, connectTitle: { color: Colors.textPrimary, fontFamily: 'Inter-Bold', fontSize: 18, marginTop: 14 }, connectText: { maxWidth: 530, color: Colors.textSecondary, fontFamily: 'Inter-Regular', fontSize: 11, lineHeight: 17, textAlign: 'center', marginTop: 7 }, connectButton: { width: '100%', minHeight: 52, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 9, borderRadius: 17, marginTop: 20, backgroundColor: '#8AB4F8' }, connectButtonText: { color: '#111217', fontFamily: 'Inter-Bold', fontSize: 12 }, disabled: { opacity: 0.45 }, refreshLink: { flexDirection: 'row', alignItems: 'center', gap: 7, padding: 12, marginTop: 6 }, refreshText: { color: '#A8C7FA', fontFamily: 'Inter-SemiBold', fontSize: 9 },
  connectionCard: { borderWidth: 1, borderColor: '#285341', borderRadius: 24, padding: 16, backgroundColor: '#14211C' }, connectionTop: { flexDirection: 'row', alignItems: 'center', gap: 12 }, connectionCheck: { width: 46, height: 46, alignItems: 'center', justifyContent: 'center', borderRadius: 15, backgroundColor: '#6EE7B714' }, connectionEyebrow: { color: '#6EE7B7', fontFamily: 'Inter-Bold', fontSize: 7, letterSpacing: 1 }, connectionTitle: { color: '#ECFDF5', fontFamily: 'Inter-Bold', fontSize: 15, marginTop: 2 }, connectionMeta: { color: '#9AB6AA', fontFamily: 'Inter-Medium', fontSize: 8.5, lineHeight: 13, marginTop: 3 }, tokenGrid: { flexDirection: 'row', gap: 8, marginTop: 13 }, tokenCard: { flex: 1, minHeight: 72, borderWidth: 1, borderColor: '#FFFFFF0C', borderRadius: 15, padding: 11, backgroundColor: '#FFFFFF06' }, tokenLabel: { color: '#6EE7B7', fontFamily: 'Inter-Bold', fontSize: 7, letterSpacing: 0.9 }, tokenValue: { color: '#C4CDC8', fontFamily: 'Inter-Medium', fontSize: 8.5, marginTop: 4 }, tokenDate: { color: '#F0F7F3', fontFamily: 'Inter-SemiBold', fontSize: 8.5, lineHeight: 13, marginTop: 2 }, connectionActions: { flexDirection: 'row', gap: 8, marginTop: 12 }, testButton: { flex: 1, minHeight: 42, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 7, borderWidth: 1, borderColor: '#41638A', borderRadius: 14, backgroundColor: '#1C2938' }, testText: { color: '#A8C7FA', fontFamily: 'Inter-Bold', fontSize: 9 }, disconnectButton: { flex: 1, minHeight: 42, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 7, borderWidth: 1, borderColor: '#733043', borderRadius: 14, backgroundColor: '#2D1920' }, disconnectText: { color: '#FDA4AF', fontFamily: 'Inter-Bold', fontSize: 9 },
  sectionHead: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginTop: 7, paddingHorizontal: 3 }, sectionKicker: { color: '#8AB4F8', fontFamily: 'Inter-Bold', fontSize: 7.5, letterSpacing: 1 }, sectionTitle: { color: Colors.textPrimary, fontFamily: 'Inter-Bold', fontSize: 18, marginTop: 3 }, deadlinePill: { flexDirection: 'row', alignItems: 'center', gap: 5, borderWidth: 1, borderColor: '#6C5420', borderRadius: 99, paddingHorizontal: 9, paddingVertical: 6, backgroundColor: '#2C2413' }, deadlineText: { color: '#FBBF24', fontFamily: 'Inter-Bold', fontSize: 8 }, environmentCard: { gap: 11, borderWidth: 1, borderColor: '#34353D', borderRadius: 22, padding: 15, backgroundColor: '#191A1F' }, environment: { flexDirection: 'row', gap: 7, borderWidth: 1, borderColor: '#39363D', borderRadius: 16, padding: 4, backgroundColor: '#141519' }, environmentButton: { flex: 1, minHeight: 42, alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: 'transparent', borderRadius: 12 }, environmentTest: { borderColor: '#4672A5', backgroundColor: '#203149' }, environmentProduction: { borderColor: '#9B6A1C', backgroundColor: '#352716' }, environmentText: { color: '#918B93', fontFamily: 'Inter-Bold', fontSize: 10 }, environmentTextActive: { color: '#FFF8F2' }, environmentHint: { color: '#9F99A1', fontFamily: 'Inter-Regular', fontSize: 9, lineHeight: 14, paddingHorizontal: 3 },
  automationCard: { borderWidth: 1, borderRadius: 22, padding: 15, backgroundColor: '#191A1F' }, automationHead: { flexDirection: 'row', alignItems: 'center', gap: 10 }, automationIcon: { width: 43, height: 43, alignItems: 'center', justifyContent: 'center', borderRadius: 14 }, automationTitle: { color: '#FFF8F2', fontFamily: 'Inter-Bold', fontSize: 14 }, automationSubtitle: { color: '#969098', fontFamily: 'Inter-Medium', fontSize: 8.5, marginTop: 2 }, modeList: { flexDirection: 'row', gap: 6, marginTop: 13 }, modeOption: { flex: 1, minHeight: 48, alignItems: 'center', justifyContent: 'center', gap: 5, borderWidth: 1, borderColor: '#3A373E', borderRadius: 14, paddingHorizontal: 5, backgroundColor: '#201E22' }, radio: { width: 18, height: 18, alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: '#5A555D', borderRadius: 9 }, modeTitle: { color: '#D6D0D7', fontFamily: 'Inter-Bold', fontSize: 8.5 }, selectedModeHint: { color: '#98929A', fontFamily: 'Inter-Regular', fontSize: 8.5, lineHeight: 13, marginTop: 8 }, delayBlock: { borderTopWidth: 1, borderTopColor: '#FFFFFF0B', paddingTop: 12, marginTop: 11 }, delayLabel: { color: '#8E8890', fontFamily: 'Inter-Bold', fontSize: 7.5, letterSpacing: 0.8 }, delayList: { flexDirection: 'row', gap: 7, marginTop: 9 }, delayButton: { flex: 1, height: 39, alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: '#49454D', borderRadius: 12, backgroundColor: '#252329' }, delayText: { color: '#C1BBC2', fontFamily: 'Inter-Bold', fontSize: 11 }, delayTextActive: { color: '#141216' }, delayHint: { color: '#878189', fontFamily: 'Inter-Regular', fontSize: 8.5, marginTop: 8 }, reminderRow: { minHeight: 74, flexDirection: 'row', alignItems: 'center', gap: 12, borderWidth: 1, borderColor: '#514329', borderRadius: 20, padding: 14, backgroundColor: '#242016' }, reminderTitle: { color: '#FFF8E7', fontFamily: 'Inter-Bold', fontSize: 11.5 }, reminderText: { color: '#A69D87', fontFamily: 'Inter-Regular', fontSize: 8.5, lineHeight: 13, marginTop: 3 }, saveButton: { minHeight: 52, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 9, borderRadius: 16, backgroundColor: '#8AB4F8' }, saveText: { color: '#151216', fontFamily: 'Inter-Bold', fontSize: 11 },
  diagnosticsCard: { borderWidth: 1, borderColor: '#315A83', borderRadius: 22, padding: 15, backgroundColor: '#17202B' }, diagnosticsHead: { flexDirection: 'row', alignItems: 'center', gap: 11 }, diagnosticsIcon: { width: 43, height: 43, alignItems: 'center', justifyContent: 'center', borderRadius: 14, backgroundColor: '#60A5FA14' }, diagnosticsKicker: { color: '#8AB4F8', fontFamily: 'Inter-Bold', fontSize: 7, letterSpacing: .8 }, diagnosticsTitle: { color: '#F4F8FF', fontFamily: 'Inter-Bold', fontSize: 14, marginTop: 2 }, diagnosticsText: { color: '#AAB6C7', fontFamily: 'Inter-Regular', fontSize: 8.5, lineHeight: 13, marginTop: 2 }, diagnosticsResults: { gap: 7, marginTop: 12 }, diagnosticRow: { minHeight: 46, flexDirection: 'row', alignItems: 'center', gap: 10, borderWidth: 1, borderColor: '#FFFFFF0C', borderRadius: 14, paddingHorizontal: 10, backgroundColor: '#FFFFFF05' }, diagnosticState: { width: 27, height: 27, alignItems: 'center', justifyContent: 'center', borderRadius: 9, backgroundColor: '#304054' }, diagnosticAccepted: { backgroundColor: '#176246' }, diagnosticRejected: { backgroundColor: '#7A2C3D' }, diagnosticStateText: { color: '#FFFFFF', fontFamily: 'Inter-Bold', fontSize: 12 }, diagnosticName: { color: '#F4F8FF', fontFamily: 'Inter-Bold', fontSize: 9.5 }, diagnosticMeta: { color: '#9EABBC', fontFamily: 'Inter-Regular', fontSize: 8, marginTop: 2 }, diagnosticsButton: { minHeight: 46, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8, borderRadius: 14, marginTop: 12, backgroundColor: '#315E91' }, diagnosticsButtonText: { color: '#F4F8FF', fontFamily: 'Inter-Bold', fontSize: 10 },
});
