SET NAMES utf8mb4;

CREATE TABLE IF NOT EXISTS `service_sheets` (
  `id`                         CHAR(36)      NOT NULL PRIMARY KEY,
  `sheet_number`               VARCHAR(40)   NOT NULL,
  `client_id`                  CHAR(36)      DEFAULT NULL,
  `qr_code`                    VARCHAR(100)  NOT NULL DEFAULT '',
  `client_name`                VARCHAR(255)  NOT NULL DEFAULT '',
  `client_phone`               VARCHAR(50)   NOT NULL DEFAULT '',
  `client_email`               VARCHAR(255)  DEFAULT NULL,
  `client_address`             TEXT          DEFAULT NULL,
  `company_name`               VARCHAR(255)  NOT NULL DEFAULT '',
  `company_fiscal_code`        VARCHAR(80)   NOT NULL DEFAULT '',
  `company_registration_number` VARCHAR(80)  NOT NULL DEFAULT '',
  `company_address`            TEXT          DEFAULT NULL,
  `company_phone`              VARCHAR(50)   DEFAULT NULL,
  `company_email`              VARCHAR(255)  DEFAULT NULL,
  `vehicle_type`               ENUM('trotineta','scuter','altul') NOT NULL DEFAULT 'trotineta',
  `vehicle_brand_model`        VARCHAR(255)  NOT NULL DEFAULT '',
  `vehicle_registration`       VARCHAR(80)   NOT NULL DEFAULT '',
  `vehicle_series`             VARCHAR(120)  NOT NULL DEFAULT '',
  `vehicle_km`                 VARCHAR(60)   NOT NULL DEFAULT '',
  `vehicle_battery`            VARCHAR(120)  NOT NULL DEFAULT '',
  `issue_description`          TEXT          DEFAULT NULL,
  `visible_damage`             TEXT          DEFAULT NULL,
  `accessories_charger`        TINYINT(1)    NOT NULL DEFAULT 0,
  `accessories_keys`           TINYINT(1)    NOT NULL DEFAULT 0,
  `accessories_saddle`         TINYINT(1)    NOT NULL DEFAULT 0,
  `accessories_other`          TINYINT(1)    NOT NULL DEFAULT 0,
  `accessories_other_text`     VARCHAR(255)  NOT NULL DEFAULT '',
  `quick_powers_on`            TINYINT(1)    NOT NULL DEFAULT 0,
  `quick_water_traces`         TINYINT(1)    NOT NULL DEFAULT 0,
  `quick_impact`               TINYINT(1)    NOT NULL DEFAULT 0,
  `quick_battery_risk`         TINYINT(1)    NOT NULL DEFAULT 0,
  `product_photo`              ENUM('da','nu','') NOT NULL DEFAULT '',
  `diagnostic`                 TEXT          DEFAULT NULL,
  `work_performed`             TEXT          DEFAULT NULL,
  `parts_used`                 TEXT          DEFAULT NULL,
  `observations`               TEXT          DEFAULT NULL,
  `diagnostic_price`           DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  `parts_price`                DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  `labor_price`                DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  `total_price`                DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  `client_package_price`       DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  `client_discount`            DECIMAL(5,2)  NOT NULL DEFAULT 0.00,
  `final_price`                DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  `deadline`                   VARCHAR(120)  NOT NULL DEFAULT '',
  `warranty`                   VARCHAR(120)  NOT NULL DEFAULT '',
  `storage_fee_per_day`        DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  `storage_after_days`         INT           NOT NULL DEFAULT 0,
  `old_parts_client`           TINYINT(1)    NOT NULL DEFAULT 0,
  `old_parts_recycle`          TINYINT(1)    NOT NULL DEFAULT 0,
  `approve_diagnostic_test`    TINYINT(1)    NOT NULL DEFAULT 0,
  `approve_repair_estimate`    TINYINT(1)    NOT NULL DEFAULT 0,
  `reject_repair`              TINYINT(1)    NOT NULL DEFAULT 0,
  `vehicle_delivered_checked`  TINYINT(1)    NOT NULL DEFAULT 0,
  `client_signature`           MEDIUMTEXT    DEFAULT NULL,
  `client_signed_at`           DATETIME      DEFAULT NULL,
  `is_finalized`               TINYINT(1)    NOT NULL DEFAULT 0,
  `finalized_at`               DATETIME      DEFAULT NULL,
  `service_pdf_base_url`        VARCHAR(500)  DEFAULT NULL,
  `service_pdf_filename`        VARCHAR(255)  DEFAULT NULL,
  `service_pdf_share_url`       VARCHAR(700)  DEFAULT NULL,
  `service_pdf_generated_at`    DATETIME      DEFAULT NULL,
  `technician_name`            VARCHAR(255)  NOT NULL DEFAULT '',
  `mechanic_name`              VARCHAR(255)  NOT NULL DEFAULT '',
  `service_type`               VARCHAR(100)  NOT NULL DEFAULT 'Verificare generala',
  `service_date`               TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `created_by`                 CHAR(36)      DEFAULT NULL,
  `updated_by`                 CHAR(36)      DEFAULT NULL,
  `created_at`                 TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at`                 TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY `uq_service_sheet_number` (`sheet_number`),
  KEY `idx_service_client` (`client_id`),
  KEY `idx_service_qr_code` (`qr_code`),
  KEY `idx_service_finalized` (`is_finalized`, `finalized_at`),
  KEY `idx_service_created` (`created_at`),
  KEY `idx_service_updated` (`updated_at`),
  KEY `idx_service_total` (`total_price`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
